# Generated by Django 5.1.6 on 2025-03-02 10:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("T", "TUITION FEE"),
                            ("C", "STUDENT CARD"),
                            ("G", "GRADUATION FEE"),
                            ("M", "MATERIALS FEE"),
                            ("I", "INTERNSHIP REPORT FEE"),
                        ],
                        max_length=1,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=16)),
                ("for_level", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "stakeholders",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("100", "GGT"),
                                ("200", "GCV"),
                                ("300", "SAE"),
                                ("400", "SIF"),
                                ("500", "MEDECINE"),
                                ("600", "ANR"),
                                ("250", "DROIT"),
                                ("350", "ENTREPRENEURIAT ET GESTION DES AFFAIRES"),
                                ("450", "SERVICE SOCIAL"),
                                ("550", "COMMUNICATION"),
                                ("650", "SCIENCES INFORMATIQUES"),
                                ("120", "OPTHAMOLOGIE"),
                                ("220", "SAGE FEMME"),
                            ],
                            max_length=3,
                        ),
                        size=None,
                    ),
                ),
                ("payable_from", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("name", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("matricule", models.IntegerField()),
                (
                    "departement",
                    models.CharField(
                        choices=[
                            ("100", "GGT"),
                            ("200", "GCV"),
                            ("300", "SAE"),
                            ("400", "SIF"),
                            ("500", "MEDECINE"),
                            ("600", "ANR"),
                            ("250", "DROIT"),
                            ("350", "ENTREPRENEURIAT ET GESTION DES AFFAIRES"),
                            ("450", "SERVICE SOCIAL"),
                            ("550", "COMMUNICATION"),
                            ("650", "SCIENCES INFORMATIQUES"),
                            ("120", "OPTHAMOLOGIE"),
                            ("220", "SAGE FEMME"),
                        ],
                        max_length=3,
                    ),
                ),
                ("promotion", models.IntegerField()),
                ("level", models.CharField(max_length=4)),
                ("speciality", models.CharField(blank=True, max_length=50, null=True)),
                ("student_check_pass", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=16)),
                ("level", models.CharField(max_length=4)),
                ("due_amount", models.DecimalField(decimal_places=3, max_digits=16)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payements",
                        to="student.academicfee",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
    ]
