# Generated by Django 5.1.6 on 2025-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="matricule",
            field=models.CharField(max_length=8),
        ),
    ]
