# Generated by Django 5.1.6 on 2025-03-01 21:03

import django.core.validators
from django.db import migrations, models

import checkstart.apps.core.validators.name
import checkstart.apps.core.validators.password


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("email", models.CharField(max_length=50, unique=True)),
                (
                    "username",
                    models.CharField(
                        max_length=50,
                        validators=[checkstart.apps.core.validators.name.str_checker],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            checkstart.apps.core.validators.password.special_characters_checker,
                            checkstart.apps.core.validators.password.uppercase_checker,
                            checkstart.apps.core.validators.password.lowercase_checker,
                            checkstart.apps.core.validators.password.number_checker,
                        ],
                        verbose_name="password",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="users_profil_photos/"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        condition=models.Q(("deleted_at", None)),
                        fields=["deleted_at"],
                        name="indexing_undeleted_users",
                    )
                ],
            },
        ),
    ]
